# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#aboutMe'
    weight: 10
  - name: Publications
    url: '#myPublications'
    weight: 20
  - name: Projects
    url: '#myProjects'
    weight: 30
  - name: Skills
    url: '#mySkills'
    weight: 40
  - name: Awards
    url: '#myAwards'
    weight: 50
  - name: Contact
    url: '#contactMe'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/resume.pdf
    weight: 70
